version: "3.8"

services:
  buchi:
    container_name: buchi
    build: .
    volumes:
      - ".:/var/www/"
      - "/var/www/node_nodules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
   
